### ISSUE TITLE
[BUG]B站二维码登录功能不能正常运行

### ISSUE THREAD

**Issue by DouDouMi00** [xqe2011/danmuji#2]
### 问题描述

B站二维码登录功能不能正常运行

### 环境信息

```
操作系统 Windows_10_22H2_19045.4046
企鹅弹幕机 v1.3.0
```

### 重现步骤

全新安装程序后运行launcher.exe

### 相关日志输出

```
[2024-02-16 12:48:29,350] ERROR in app: Exception
Traceback (most recent call last):
  File "quart\app.py", line 1553, in _wrapper
  File "quart\ctx.py", line 343, in wrapper
  File "app\live.py", line 189, in initalizeLive
  File "concurrent\futures\thread.py", line 58, in run
  File "app\live.py", line 136, in loginBili
  File "bilibili_api\login_func.py", line 45, in get_qrcode
  File "bilibili_api\login.py", line 89, in update_qrcode_data
  File "httpx\_models.py", line 755, in json
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by xqe2011** [comment]
我复现一下

**Comment by xqe2011** [comment]
已确认问题，正在修复

**Comment by xqe2011** [comment]
上游库的问题，我先自己写登陆函数用着

**Comment by DouDouMi00** [comment]
### 尝试升级bilibili-api-python==16.2.0
二维码可以正常显示，但扫描登录后报错
```
[2024-02-16 14:02:24,221] [Live] 等待二维码登录中...
Exception in Tkinter callback
Traceback (most recent call last):
  File "g:\python\danmuji\.conda\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "g:\python\danmuji\.conda\Lib\tkinter\__init__.py", line 861, in callit
    func(*args)
  File "G:\python\danmuji\app\live.py", line 155, in update
    event, cred = login_func.check_qrcode_events(token)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\python\danmuji\.conda\Lib\site-packages\bilibili_api\login_func.py", line 69, in check_qrcode_events
    url: str = events["data"]["url"]
               ~~~~~~^^^^^^^^
KeyError: 'data'
```
我删除bilibili_api\login_func.py 69行，改为
```
url: str = events["url"]
```
然后运行，可以正常登录
### 新问题
bilibili-api-python==16.2.0 要求库版本，与blivedm要求冲突
```
aiohttp~=3.9.3
Brotli==1.1.0
```

**Comment by xqe2011** [comment]
是的，已经修好了，现在正在提交

**Comment by xqe2011** [comment]
#c1aed17 尝试修复了这个问题，但是不知道更新blivedm是否会导致其他可能的问题，得等我晚上回去看看

**Comment by DouDouMi00** [comment]
更新bilibili_api后，pyinstaller launcher.spec命令,bilibili_api 的数据没有打包进去。
解决方法
https://github.com/Nemo2011/bilibili-api/issues/39#issue-1337964537

**Comment by xqe2011** [comment]
收到，待会一起处理了

**Comment by xqe2011** [comment]
57e8c6e681a8569e5519604797abbe06e59624ac 已修复

**Comment by xqe2011** [comment]
[latest](https://github.com/xqe2011/danmuji/releases/tag/latest)试试

**Comment by DouDouMi00** [comment]
试了下，问题已解决，非常感谢抽出时间来修复它。👍

**Comment by z0z0r4** [comment]
> ### 尝试升级bilibili-api-python==16.2.0
> 二维码可以正常显示，但扫描登录后报错
> 
> ```
> [2024-02-16 14:02:24,221] [Live] 等待二维码登录中...
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "g:\python\danmuji\.conda\Lib\tkinter\__init__.py", line 1948, in __call__
>     return self.func(*args)
>            ^^^^^^^^^^^^^^^^
>   File "g:\python\danmuji\.conda\Lib\tkinter\__init__.py", line 861, in callit
>     func(*args)
>   File "G:\python\danmuji\app\live.py", line 155, in update
>     event, cred = login_func.check_qrcode_events(token)
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "g:\python\danmuji\.conda\Lib\site-packages\bilibili_api\login_func.py", line 69, in check_qrcode_events
>     url: str = events["data"]["url"]
>                ~~~~~~^^^^^^^^
> KeyError: 'data'
> ```
> 
> 我删除bilibili_api\login_func.py 69行，改为
> 
> ```
> url: str = events["url"]
> ```
> 
> 然后运行，可以正常登录
> 
> ### 新问题
> bilibili-api-python==16.2.0 要求库版本，与blivedm要求冲突
> 
> ```
> aiohttp~=3.9.3
> Brotli==1.1.0
> ```

其实建议使用 dev 分支的 pip 包，没人发正式版更新 =-=

**Comment by DouDouMi00** [comment]
好的喵～  （才发现波浪号，也有中英文区分）

**Comment by xqe2011** [comment]
好的喵，下个版本更新上去
